config/routes.rb
Rails.application.routes.draw do
  root to: 'products#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  resources :top, only: [:index, :new, :create, :show, :edit, :update]
  resources :users, only: [:show,:logout]
  
  namespace :api do
    resources :categories, only: :index, defaults: { format: 'json' }
  end
 

  resources :products do
    member do
      get 'purchase'
      post 'pay'
    end
  end
  
  resources :cards, only: [:new, :show,:index ,:delete] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true
  validates :email, presence: true
  validates :password, presence: true
  validates :family_name, presence: true,format: { with: /\A[一-龥]+\z/, message: 'は漢字を入力してください'}
  validates :first_name, presence: true,format:{ with: /\A[一-龥]+\z/, message: 'は漢字を入力してください'}
  validates :hurigana_family_name, presence: true,format:{ with: /\A[ぁ-んー－]+\z/, message: 'は全角平仮名を入力してください'}
  validates :hurigana_first_name, presence: true,format:{ with: /\A[ぁ-んー－]+\z/, message: 'は全角平仮名を入力してください'}
  validates :birth_year, presence: true
  validates :birth_month, presence: true
  validates :birth_date, presence: true



  has_many :cards
  has_one :address
  accepts_nested_attributes_for :address
  
  has_many :comennts
  has_many :favorites
  has_many :products
         
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :configure_sign_up_params, only: [:create]


 def index
 end


  def new
    @user = User.new
  end

  def create
    @user = User.new(sign_up_params)
    unless @user.valid?
      flash.now[:alert] = @user.errors.full_messages
      render :new and return
    end
    session["devise.regist_data"] = {user: @user.attributes}
    session["devise.regist_data"][:user]["password"] = params[:user][:password]
    @address = @user.build_address
    render :new_address
  end

  def create_address
    @user = User.new(session["devise.regist_data"]["user"])
    @address = Address.new(address_params)
    unless @address.valid?
      flash.now[:alert] = @address.errors.full_messages
      render :new_address and return
    end
    @user.build_address(@address.attributes)
    @user.save
    sign_in(:user, @user)
  end

  protected
  
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end
  
  def address_params
    params.require(:address).permit(:postal_code,:administrative＿divisions,:city,:street_number,:apartment,:tel)
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def show
    @user = User.where(user_id: current_user.id)
  end
  
  def logout
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<h2>Resend unlock instructions</h2>

<%= form_for(resource, as: resource_name, url: unlock_path(resource_name), html: { method: :post }) do |f| %>
  <%= render "devise/shared/error_messages", resource: resource %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="actions">
    <%= f.submit "Resend unlock instructions" %>
  </div>
<% end %>

<%= render "users/shared/links" %>

app/views/users/show.html.haml
.top_body
  .headerBox
    .headerBox__upperBox
      .headerBox__upperBox__furimaIcon
        = link_to root_path do
          = image_tag "logo.png", hight:"60px", width: "160px"
      .headerBox__upperBox__search
        = form_tag("#", method: :get) do
          = text_field_tag("text", "",{placeholder: "キーワードから探す", class: "text111"})
        .headerBox__upperBox__search__searchIcon 
          = image_submit_tag "icon-search 1.png",width: "50px", height: "44px"
    .headerBox__lowerBox  
      .headerBox__lowerBox__leftBox
        .headerBox__lowerBox__leftBox__category
          カテゴリー
        .headerBox__lowerBox__leftBox__brand
          ブランド
      .headerBox__lowerBox__rightBox
        .headerBox__lowerBox__rightBox__login
          - if user_signed_in?
            .headerBox__lowerBox__rightBox__login__registration
              = link_to "ログアウト",destroy_user_session_path, method: :delete, class: "logout_btn"
            .headerBox__lowerBox__rightBox__login__registration
              = link_to "マイページ",user_path(current_user),class: "logout_btn"
          - else
            .headerBox__lowerBox__rightBox__login__registration
              = link_to "ログイン", new_user_session_path, class: "login_btn"
            .headerBox__lowerBox__rightBox__login__registration
              = link_to "新規登録", new_user_registration_path,class: "login_btn"
    .headerBox__pan
      - breadcrumb :mypage
      = breadcrumbs separator: " &rsaquo; ", class: "breadcrumbs-list"
  .mypage
    .mypage__free
      .mypage__free__icon
        .mypage__free__icon__box
          .mypage__free__icon__box__profile
            = image_tag 'member_photo_noimage_thumb.png', height: '60px', width: '60px'
            .mypage__free__icon__box__profile__name
              = current_user.nickname
              さん
            .mypage__free__icon__box__profile__detail
              評価数0 出品数0
            .mypage__free__card
              = link_to '➕ クレジットカード登録', "/cards/new", class: "method"
      .mypage__free__item
        出品商品
      .mypage__free__items
        =image_tag  "a007.png"
        =image_tag  "a001.png"
        =image_tag  "a004.png"
        =image_tag  "a001.png"
        =image_tag  "a004.png"
        =image_tag  "a007.png"
        =image_tag  "a004.png"
        =image_tag  "a007.png"
        =image_tag  "a001.png"
        =image_tag  "a007.png"
        =image_tag  "a001.png"
        =image_tag  "a004.png"
        =image_tag  "a001.png"
        =image_tag  "a004.png"
        =image_tag  "a007.png"
        =image_tag  "a004.png"
        =image_tag  "a007.png"
        =image_tag  "a001.png"

  = render 'layouts/footer'