config/routes.rb
Rails.application.routes.draw do
  root to: 'products#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  resources :top, only: [:index, :new, :create, :show, :edit, :update]
  resources :users, only: [:show,:logout]
  
  namespace :api do
    resources :categories, only: :index, defaults: { format: 'json' }
  end
 

  resources :products do
    member do
      get 'purchase'
      post 'pay'
    end
  end
  
  resources :cards, only: [:new, :show,:index ,:delete] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end
end

app/models/card.rb
class Card < ApplicationRecord
  # validates :customer_id, :card_id, presence: true
  belongs_to :user
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  require 'payjp'

  def index
  end
  
  def new
    card = Card.where(user_id: current_user.id)
    redirect_to action: "show" if card.exists?
  end
  
  def pay
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create( # ここで先ほど生成したトークンを顧客情報と紐付け、PAY.JP管理サイトに送信
        description: 'test',
        email: current_user.email,
        card: params['payjp-token'],
        metadata: {user_id: current_user.id}
      )
    @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "show"
        flash[:notice] = 'クレジットカードの登録が完了しました'
      else
        redirect_to action: "pay"
        flash[:alert] = 'クレジットカード登録に失敗しました'
      end
    end
  end

  def delete #PayjpとCardデータベースを削除します
    card = Card.where(user_id: current_user.id).first
    if card.blank?
    else
      Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
      flash[:notice] = "削除しました。"
    end
      redirect_to action: "new"
  end


  def show #Cardのデータpayjpに送り情報を取り出します
    card = Card.where(user_id: current_user.id).first
    if card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end


  
end

  

app/helpers/card_helper.rb
module CardHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/buy.html.haml
.confirmation
  .confirmation__header
    = link_to root_path do
      = image_tag "logo.png", size: "185x49"

  .confirmation__contents
    .confirmation__contents__box
      .confirmation__contents__box__head
        購入内容の確認
      .confirmation__contents__box__items
        .confirmation__contents__box__items__inner
          .confirmation__contents__box__items__inner__box1
            .confirmation__contents__box__items__inner__box1__image
              = image_tag "a007.png", size: "80x80"
            .confirmation__contents__box__items__inner__box1__detail
              .confirmation__contents__box__items__inner__box1__detail__name
                %p サロンドアルファードファーハンドバッグ
              .confirmation__contents__box__items__inner__box1__detail__price
                %p ¥5000 (税込み)送料込み
      .confirmation__contents__box__info
        .confirmation__contents__box__info__paybox
          .confirmation__contents__box__info__paybox__pay
            %p 支払い金額
          .confirmation__contents__box__info__paybox__money
            %p ¥5000
        .confirmation__contents__box__info__paybox__point
          %p □ ポイントを使用 (所持ポイント: P0)

        .confirmation__contents__box__info__methodbox
          .confirmation__contents__box__info__methodbox__method
            %p 支払い方法
          .confirmation__contents__box__info__methodbox__registration
            = link_to "➕登録してください", "/cards/new" , class: 'aaa'

        .confirmation__contents__box__info__addressbox
          .confirmation__contents__box__info__addressbox__deli
            %p 配送先
          .confirmation__contents__box__info__addressbox__change
            = link_to "変更する", '/#' , class: 'bbb'
        .confirmation__contents__box__info__individual
          %p 〒123-4567
          %p aaa県 bbb市 ccc町123
          %p あいう えお 
        .confirmation__contents__box__info__purchase
          .confirmation__contents__box__info__purchase__button
            = link_to "購入する", "/#" , class: 'ccc'

  .confirmation__footer
    .confirmation__footer__content
      = link_to 'プライバシーポリシー', '/#', class: 'hoge-last'
      = link_to 'フリマ利用規約', '/#', class: 'hoge-last'
      = link_to '特定商取引に関する表記', '/#', class: 'hoge-last'
      %br
      = image_tag "logo-white.png", size: "185x49", class: 'hoge-last'
      %br
      %small © FURIMA, Inc.

app/views/cards/new.html.haml
.top_flash
  - if flash[:notice]
    %p= flash[:notice]
  - else flash[:notice] 
    
.card_body
  .top_body
    .headerBox
      .headerBox__upperBox
        .headerBox__upperBox__furimaIcon
          = link_to root_path do
            = image_tag "logo.png", hight:"60px", width: "160px"
        .headerBox__upperBox__search
          = form_tag("#", method: :get) do
            = text_field_tag("text", "",{placeholder: "キーワードから探す", class: "text111"})
          .headerBox__upperBox__search__searchIcon 
            = image_submit_tag "icon-search 1.png",width: "50px", height: "44px"
      .headerBox__lowerBox  
        .headerBox__lowerBox__leftBox
          .headerBox__lowerBox__leftBox__category
            カテゴリー
          .headerBox__lowerBox__leftBox__brand
            ブランド
        .headerBox__lowerBox__rightBox
          .headerBox__lowerBox__rightBox__login
            - if user_signed_in?
              .headerBox__lowerBox__rightBox__login__registration
                = link_to "ログアウト",destroy_user_session_path, method: :delete, class: "logout_btn"
              .headerBox__lowerBox__rightBox__login__registration
                = link_to "マイページ",user_path(current_user),class: "logout_btn"
            - else
              .headerBox__lowerBox__rightBox__login__registration
                = link_to "ログイン", new_user_session_path, class: "login_btn"
              .headerBox__lowerBox__rightBox__login__registration
                = link_to "新規登録", new_user_registration_path,class: "login_btn"
      .headerBox__lowerBox__pan
        - breadcrumb :registration 
        = breadcrumbs separator: " &rsaquo; ", class: "breadcrumbs-list"    

  .credit-update
    .credit-update__box
      .credit-update__box__label
        クレジットカード情報入力
      .card-form
        .card-form__box
          = form_tag(pay_cards_path, method: :post, id: 'charge-form',  name: "inputForm",html: { class: "form_card" }) do
            .card-form__box__number
              %label{class:'box-group--label', for: 'card_number'} カード番号
              %span.input-require
                必須
              = text_field_tag "number", "", class: "card-number--input", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
              %ul.card-list
                %li.card-list--item{ style: "margin-left: 0;"}
                  = image_tag "card.PNG",size: "377x70"

            .card-form__box__expire
              %label.box-group--label 有効期限
              %span.input-require
                必須
              .card-expire
                .card-expire__select-month
                  %select#exp_month{name: "exp_month", type: "text",class: "select_select"}
                    %option{value: ""} --
                    %option{value: "1"}01
                    %option{value: "2"}02
                    %option{value: "3"}03
                    %option{value: "4"}04
                    %option{value: "5"}05
                    %option{value: "6"}06
                    %option{value: "7"}07
                    %option{value: "8"}08
                    %option{value: "9"}09
                    %option{value: "10"}10
                    %option{value: "11"}11
                    %option{value: "12"}12
                  %i.card-form-expire-icon
                  %span{class: "month"}  月/
                .card-expire__select-year
                  %select#exp_year{name: "exp_year", type: "text"}
                    %option{value: ""} --
                    %option{value: "2019"}19
                    %option{value: "2020"}20
                    %option{value: "2021"}21
                    %option{value: "2022"}22
                    %option{value: "2023"}23
                    %option{value: "2024"}24
                    %option{value: "2025"}25
                    %option{value: "2026"}26
                    %option{value: "2027"}27
                    %option{value: "2028"}28
                    %option{value: "2029"}29
                  %i.card-form-expire-icon
                  %span{class:"year"} 年
              .card-form__box__security-code
                %label.box-group--label{for: "cvc"} セキュリティーコード
                %span.input-require
                  必須
                = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc",class: 'payment__security-code'
                .question-form
                  %span.question-form__mark ?
                  %span.question-form__text 
                    カード裏面の番号とは？
              #card_token
              = submit_tag "追加する", id: "token_submit",class: "card-form__box__add", type: 'button'
  .payment__footer
    .payment__footer__content
      = link_to 'プライバシーポリシー', '/#', class: 'hoge-last'
      = link_to 'フリマ利用規約', '/#', class: 'hoge-last'
      = link_to '特定商取引に関する表記', '/#', class: 'hoge-last'
      %br
      = image_tag "logo-white.png", size: "185x49", class: 'hoge-last'
      %br
      %small © FURIMA, Inc.

app/views/cards/show.html.haml
.payment
  .top_flash
    - if flash[:notice]
      %p= flash[:notice]
  .payment__header
    = link_to root_path do
      = image_tag "logo.png", size: "185x49"
  .payment__contents
    .payment__contents__box
      .payment__contents__box__method
        クレジットカード一覧
      .payment__contents__box__cards
        .payment__contents__box__number
          %label 登録クレジットカード情報
          %br
          = "**** **** **** " + @default_card_information.last4
          %br
          - exp_month = @default_card_information.exp_month.to_s
          - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
          = exp_month + " / " + exp_year
          %br
        .payment__contents__box__cards__delete
          = form_tag(delete_cards_path, method: :post, id: 'charge-form',  name: "inputForm") do
            %input{ type: "hidden", name: "card_id", value: "" }
            = submit_tag "削除する",class: "destroy_btn"
  .payment__footer
    .payment__footer__content
      = link_to 'プライバシーポリシー', '/#', class: 'hoge-last'
      = link_to 'フリマ利用規約', '/#', class: 'hoge-last'
      = link_to '特定商取引に関する表記', '/#', class: 'hoge-last'
      %br
      = image_tag "logo-white.png", size: "185x49", class: 'hoge-last'
      %br
      %small © FURIMA, Inc.