config/routes.rb
Rails.application.routes.draw do
  root to: 'products#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  resources :top, only: [:index, :new, :create, :show, :edit, :update]
  resources :users, only: [:show,:logout]
  
  namespace :api do
    resources :categories, only: :index, defaults: { format: 'json' }
  end
 

  resources :products do
    member do
      get 'purchase'
      post 'pay'
    end
  end
  
  resources :cards, only: [:new, :show,:index ,:delete] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord

has_many :images, dependent: :destroy
accepts_nested_attributes_for :images, allow_destroy: true

belongs_to :category
belongs_to :user
belongs_to :seller, class_name: "User", optional: true
belongs_to :buyer, class_name: "User", optional: true

validates :delivery_charge, :prefecture, :delivery_day, :text, :price, presence: true
validates :name,        presence: true,
                        length: { minimum: 1, maximum: 40 }
validates :conditions,  presence: true,
                        length: { minimum: 1, maximum: 1000 }

validates :images,      presence: true

  validates :name, :price, :text, presence: true
extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :todoufuken
  belongs_to_active_hash :delivery

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  require 'payjp'
  before_action :authenticate_user!, only: [:purchase,:new]
  before_action :set_product, except: [:index, :new, :create, :update]
  
    def index
      @products = Product.includes(:images).order('created_at DESC')
    end

    def new
      @product = Product.new
      @product.images.new
    end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to root_path, notice: 'Event was successfully created.'
    else
      render :new
    end
  end
 
  
  def edit
    @products = Product.find(params[:id])
  end
  
  def update
    product = Product.find(params[:id])
    if product.update(product_params)
      flash[:notice] = "編集しました。"
      redirect_to
    else
      flash[:notice] = "必須項目が空欄です。"
      redirect_to edit_product_path(product.id)
    end
  end

  def destroy
    @product = Product.find(params[:id])
    if  @product.destroy
      flash[:notice] = "削除しました。"
    else
      flash[:notice] = "削除失敗しました。"
    end
    redirect_to  root_path
  end
  
  
  def show
    @images = @product.images
    @categories = Category.find(params[:id])
    @user = User.find_by(params[:id])
  end
  
  def purchase 
    @user = User.find_by(params[:id])
    @address = Address.find_by(id:2)
    card = Card.where(user_id: current_user.id).first
    #Cardテーブルは前回記事で作成、テーブルからpayjpの顧客IDを検索
    if card.blank?
      #登録された情報がない場合にカード登録画面に移動
      redirect_to controller: "cards", action: "new"
      flash[:notice] = '購入にはクレジットカード登録が必要です'
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      #保管した顧客IDでpayjpから情報取得
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
      #保管したカードIDでpayjpから情報取得、カード情報表示のためインスタンス変数に代入
    end
  end

  def pay
      card = Card.where(user_id: current_user.id).first
      Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
      charge = Payjp::Charge.create(
        amount: @product.price,
        customer: card.customer_id,
        currency: 'jpy',
      )
      @product.update( buyer_id: current_user.id)
      flash[:notice] = '購入しました。'
      redirect_to  action: 'index'
  end
      
      
      
  private
  
  def product_params
    params.require(:product).permit(:name, :conditions, :delivery_charge, :prefecture, :delivery_day, :text, :category_id, :brand_id, :price, images_attributes:  [:src, :_destroy, :id]).merge(user_id: current_user.id)
  end
      
  def set_product
    @product = Product.find(params[:id])
  end

end

 
    

    

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.haml
= form_for @product do |f|

  .exhibition__header
    = link_to root_path do
      = image_tag "logo.png", size: "185x49"
  .exhibition__contents__main
    .exhibition__contents__main__middle
      .exhibition__contents__main__middle__head
        商品の情報を入力
      .exhibition__contents__main__middle__heart
        .exhibition__contents__main__middle__heart__upload-box
          
          .exhibition__contents__main__middle__heart__upload-box__title
            出品画像
            %span.exhibition-essential
              必須
              

                          
            .exhibition__contents__main__middle__heart__upload-box__explain
              最大10枚までアップロードできます
          
              %b
                ドラッグアンドドロップ
                %br
                またはクリックしてファイルをアップロード
              

            = f.fields_for :images do |image|
              .js-file_group{"data-index":"#{image.index}"} 
                = image.file_field :src, class: 'js-file'
                %span.js-remove 削除
              - if @product.persisted? 
                = image.check_box :_destroy, data:{ index: image.index }, class: 'hidden-destroy' 

              - if @product.persisted?
                .js-file_group{"data-index" => "#{@product.images.count}"}
                  = file_field_tag :src, name: "product[images_attributes][#{@product.images.count}][src]", class: 'js-file'
                  .js-remove 削除


        .exhibition__contents__main__middle__heart__sell-content
          
          .exhibition__contents__main__middle__heart__sell-content__form-one
            商品名
            %span.exhibition-essential 必須
            = f.text_field :name, class: 'exhibition__contents__main__middle__heart__sell-content__form-one__name', placeholder: '  商品名 (必須40文字まで)'
          .exhibition__contents__main__middle__heart__sell-content__form-group
            商品の説明
            %span.exhibition-essential 必須
            = f.text_area :text, class: 'exhibition__contents__main__middle__heart__sell-content__form-group__explain', placeholder: '商品名 （商品の説明(必須1,000文字以内）（色、素材、重さ、定価、注意点など）例）   2010年頃に1万円に購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。）'
        .exhibition__contents__main__middle__heart__detail
          商品の詳細
          .exhibition__contents__main__middle__heart__detail__sell-form-box
            .exhibition__contents__main__middle__heart__detail__sell-form-box__category.js-category_box
              カテゴリー
              %span.exhibition-essential 必須
              = f.select :category_id, [ ["レディース",1], ["メンズ", 2], ["ベビー・キッズ", 3], ["インテリア・住まい・小物", 4], ["本・音楽・ゲーム", 5], ["おもちゃ・ホビー・グッズ", 6], ["コスメ・香水・美容", 7], ["家電・スマホ・カメラ", 8] ,["スポーツ・レジャー", 9], ["ハンドメイド", 10], ["チケット", 11], ["自動車・オートバイ", 12], ["その他", 13] ], prompt: "---", id: 'aa_theme'
            .exhibition__contents__main__middle__heart__detail__sell-form-box__status
              商品の状態
              %span.exhibition-essential 必須
              = f.select :conditions, [ ["新品、未使用",1], ["未使用に近い", 2], ["目立った傷や汚れなし", 3], ["やや傷や汚れなし", 4], ["傷や汚れなし", 5], ["傷や汚れあり", 6], ["全体的に状態が悪い", 7] ], prompt: "---", id: 'aa_theme'
        .exhibition__contents__main__middle__heart__delivery
          配送について
          .exhibition__contents__main__middle__heart__delivery__sell-form-box
            配送料の負担
            %span.exhibition-essential 必須
            = f.select :delivery_charge, [ ["送料込み(出品者負担)",1], ["着払い(購入者負担)", 2] ], prompt: "---", id: 'aa_theme'
            .exhibition__contents__main__middle__heart__delivery__sell-form-box__area
              発送元の地域
              %span.exhibition-essential 必須
              = f.select :prefecture, [ ["北海道",1], ["青森県", 2], ["岩手県", 3], ["宮城県", 4], ["秋田県", 5], ["山形県", 6], ["福島県", 7], ["茨城県", 8], ["栃木県", 9], ["群馬県", 10], ["埼玉県", 11], ["千葉県", 12], ["東京都", 13], ["神奈川県", 14], ["新潟県", 15], ["富山県", 16], ["石川県", 17], ["福井県", 18], ["山梨県", 19], ["長野県", 20], ["岐阜県", 21], ["静岡県", 22], ["愛知県", 23], ["三重県", 24], ["滋賀県", 25], ["京都府", 26], ["大阪府", 27], ["京都府", 28], ["奈良県", 29], ["和歌山県", 30], ["鳥取県", 31], ["島根県", 32], ["岡山県", 33], ["広島県", 34], ["山口県", 35], ["徳島県", 36], ["香川県", 37], ["愛媛県", 38], ["高知県", 39], ["福岡県", 40], ["佐賀県", 41], ["長崎県", 42], ["熊本県", 43], ["大分県", 44], ["宮崎県", 45], ["鹿児島県", 46], ["沖縄県", 47], ["未定", 48] ], prompt: "---", id: 'aa_theme'
            .exhibition__contents__main__middle__heart__delivery__sell-form-box__date
              発送までの日数
              %span.exhibition-essential 必須
              = f.select :delivery_day, [ ["1~2日で発送",1], ["2~3日で発送", 2], ["4~7日で発送", 3] ], prompt: "---", id: 'aa_theme'
        .exhibition__contents__main__middle__heart__money
          販売価格(300~9,999,999)
          .exhibition__contents__main__middle__heart__money__sell-box
            .exhibition__contents__main__middle__heart__money__sell-box__form-group
              .exhibition__contents__main__middle__heart__money__sell-box__form-group__left
                価格
                %span.exhibition-essential 必須
              .exhibition__contents__main__middle__heart__money__sell-box__form-group__right
                ¥
                .exhibition__contents__main__middle__heart__money__sell-box__form-group__right__money
                  = f.text_field :price, class: 'right__money', placeholder: '例） 300   '
        .exhibition__contents__main__middle__heart__bottom
          = link_to '禁止されている出品', '/#/', class: 'hoge-hoge'
          、
          = link_to '行為', '/#/', class: 'hoge-hoge'
          を必ずご確認ください。
          またブランド品でシリアルナンバー等がある場合はご記載ください。
          = link_to '偽ブランドの販売', '/#', class: 'hoge-hoge'
          は犯罪であり処罰される可能性があります。
          また、出品をもちまして
          = link_to '加盟店規約', '/#/', class: 'hoge-hoge'
          に同意したことになります。
          .exhibition__contents__main__middle__heart__bottom__display
            = f.submit "出品する"
          .exhibition__contents__main__middle__heart__bottom__back
            = link_to 'もどる', '/#/', class: 'hoge-btn'
  .exhibition__footer
    .exhibition__footer__content
      = link_to 'プライバシーポリシー', '/#', class: 'hoge-last'
      = link_to 'メルカリ利用規約', '/#', class: 'hoge-last'
      = link_to '特定商取引に関する表記', '/#', class: 'hoge-last'
      %br
      = image_tag "logo-white.png", size: "185x49", class: 'hoge-last'
      %br
      %small © FURIMA, Inc.

app/views/products/_product.html.haml
.SyouhinnSyousai
  %p 
    = product.name
  %p
    = product.price
  - product.images.each do |image|
    = image_tag image.src.url
    = link_to '編集', root_path
    -# = link_to '編集', edit_product_path(product_id)



-# <%# <div class="SyouhinnSyousai">
-#   <p><%= product.name %></p>
-#   <p><%= product.price %>円</p>
-#   <% product.images.each do |image| %>
-#     <%= image_tag image.src.url %>
-#     <%= link_to '編集', edit_product_path(product) %>
-#   <% end %>
-# </div> %>

app/views/products/edit.html.haml
= render 'layouts/notifications'
= form_for @product do |f|
  .exhibition__header
    = link_to root_path do
      = image_tag "logo.png", size: "185x49"
  .exhibition__contents__main
    .exhibition__contents__main__middle
      .exhibition__contents__main__middle__head
        商品の情報を入力
      .exhibition__contents__main__middle__heart
        .exhibition__contents__main__middle__heart__upload-box
          .exhibition__contents__main__middle__heart__upload-box__title
            出品画像
            %span.exhibition-essential
              必須
            .exhibition__contents__main__middle__heart__upload-box__title_a
              最大10枚までアップロードできます
            .exhibition__contents__main__middle__heart__upload-box__explain
            .exhibition__contents__main__middle__heart__upload-box__item
              - @product.images.each do |image|
                = image_tag image.src.url, size: "114x85", class: "aaaaa"
              = f.fields_for :images do |image|
                -# = image.file_field :images

                
                .js-file_group{"data-index":"#{image.index}"}
                  = image.file_field :src, class: 'js-file'
                  %span.js-remove 削除
                - if @product.persisted?
                  = image.check_box :_destroy, data:{ index: image.index }, class: 'hidden-destroy'
              - if @product.persisted?
                .js-file_group{"data-index" => "#{@product.images.count}"}
                  = file_field_tag :src, name: "product[images_attributes][#{@product.images.count}][src]", class: 'js-file'
                  %span.js-remove 削除
             

        .exhibition__contents__main__middle__heart__sell-content
          .exhibition__contents__main__middle__heart__sell-content__form-one
            商品名
            %span.exhibition-essential 必須
            = f.text_field :name, class: 'exhibition__contents__main__middle__heart__sell-content__form-one__name', placeholder: '  商品名 (必須40文字まで)'
          .exhibition__contents__main__middle__heart__sell-content__form-group
            商品の説明
            %span.exhibition-essential 必須
            = f.text_area :text, class: 'exhibition__contents__main__middle__heart__sell-content__form-group__explain', placeholder: '商品名 （商品の説明(必須1,000文字以内）（色、素材、重さ、定価、注意点など）例）   2010年頃に1万円に購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。）'
        .exhibition__contents__main__middle__heart__detail
          商品の詳細
          .exhibition__contents__main__middle__heart__detail__sell-form-box
            .exhibition__contents__main__middle__heart__detail__sell-form-box__category.js-category_box
              カテゴリー
              %span.exhibition-essential 必須
              = f.collection_select :category_id, Category.roots, :id, :name,  {prompt: "---"}, class: "js-category"
            .exhibition__contents__main__middle__heart__detail__sell-form-box__status
              商品の状態
              %span.exhibition-essential 必須
              = f.select :conditions, [ ["新品、未使用","新品、未使用"], ["未使用に近い", "未使用に近い"], ["目立った傷や汚れなし", "目立った傷や汚れなし"], ["やや傷や汚れなし", "やや傷や汚れなし"], ["傷や汚れなし", "傷や汚れなし"], ["傷や汚れあり", "傷や汚れあり"], ["全体的に状態が悪い", "全体的に状態が悪い"] ], prompt: "---", id: 'aa_theme'
        .exhibition__contents__main__middle__heart__delivery
          配送について
          .exhibition__contents__main__middle__heart__delivery__sell-form-box
            配送料の負担
            %span.exhibition-essential 必須
            = f.select :delivery_charge, [ ["送料込み(出品者負担)","送料込み(出品者負担)"], ["着払い(購入者負担)", "着払い(購入者負担)"] ], prompt: "---", id: 'aa_theme'
            .exhibition__contents__main__middle__heart__delivery__sell-form-box__area
              発送元の地域
              %span.exhibition-essential 必須
              = f.select :prefecture, [ ["北海道","北海道"], ["青森県", "青森県"], ["岩手県", "岩手県"], ["宮城県", "宮城県"], ["秋田県", "秋田県"], ["山形県", "山形県"], ["福島県", "福島県"], ["茨城県", "茨城県"], ["栃木県", "栃木県"], ["群馬県", "群馬県"], ["埼玉県", "埼玉県"], ["千葉県","千葉県"], ["東京都", "東京都"], ["神奈川県", "神奈川県"], ["新潟県","新潟県"], ["富山県", "富山県"], ["石川県", "石川県"], ["福井県", "福井県"], ["山梨県","山梨県"], ["長野県","長野県"], ["岐阜県","岐阜県"], ["静岡県", "静岡県"], ["愛知県", "愛知県"], ["三重県", "三重県"], ["滋賀県", "滋賀県"], ["京都府", "京都府"], ["大阪府", "大阪府"], ["京都府", "京都府"], ["奈良県", "奈良県"], ["和歌山県", "和歌山県"], ["鳥取県", "鳥取県"], ["島根県", "島根県"], ["岡山県", "岡山県"], ["広島県", "広島県"], ["山口県", "山口県"], ["徳島県", "徳島県"], ["香川県", "香川県"], ["愛媛県", "愛媛県"], ["高知県", "高知県"], ["福岡県", "福岡県"], ["佐賀県", "佐賀県"], ["長崎県", "長崎県"], ["熊本県", "熊本県"], ["大分県", "大分県"], ["宮崎県", "宮崎県"], ["鹿児島県", "鹿児島県"], ["沖縄県", "沖縄県"], ["未定", "未定"] ], prompt: "---", id: 'aa_theme'
            .exhibition__contents__main__middle__heart__delivery__sell-form-box__date
              発送までの日数
              %span.exhibition-essential 必須
              = f.select :delivery_day, [ ["1~2日で発送","1~2日で発送"], ["2~3日で発送", "2~3日で発送"], ["4~7日で発送", "4~7日で発送"] ], prompt: "---", id: 'aa_theme'
        .exhibition__contents__main__middle__heart__money
          販売価格(300~9,999,999)
          .exhibition__contents__main__middle__heart__money__sell-box
            .exhibition__contents__main__middle__heart__money__sell-box__form-group
              .exhibition__contents__main__middle__heart__money__sell-box__form-group__left
                価格
                %span.exhibition-essential 必須
              .exhibition__contents__main__middle__heart__money__sell-box__form-group__right
                ¥
                .exhibition__contents__main__middle__heart__money__sell-box__form-group__right__money
                  = f.text_field :price, class: 'right__money', placeholder: '例） 300   '
        .exhibition__contents__main__middle__heart__bottom
          = link_to '禁止されている出品', '/#/', class: 'hoge-hoge'
          、
          = link_to '行為', '/#/', class: 'hoge-hoge'
          を必ずご確認ください。
          またブランド品でシリアルナンバー等がある場合はご記載ください。
          = link_to '偽ブランドの販売', '/#', class: 'hoge-hoge'
          は犯罪であり処罰される可能性があります。
          また、出品をもちまして
          = link_to '加盟店規約', '/#/', class: 'hoge-hoge'
          に同意したことになります。
          .exhibition__contents__main__middle__heart__bottom__display
            -# = link_to '出品する', '/#/', class: 'hoge-btn'
            = f.submit "編集する", class: 'exhibition_btn'
          .exhibition__contents__main__middle__heart__bottom__back
            = link_to 'もどる', '/#/', class: 'hoge-btn'
  .exhibition__footer
    .exhibition__footer__content
      = link_to 'プライバシーポリシー', '/#', class: 'hoge-last'
      = link_to 'メルカリ利用規約', '/#', class: 'hoge-last'
      = link_to '特定商取引に関する表記', '/#', class: 'hoge-last'
      %br
      = image_tag "logo-white.png", size: "185x49", class: 'hoge-last'
      %br
      %small © FURIMA, Inc.

app/views/products/index.html.haml
.top_body
  .top_flash
    - if flash[:notice]
      %p= flash[:notice]
  = render 'layouts/header'
  .Topimage
    .TopImage
      = image_tag "bg-mainVisual-pict_pc.jpg", height:"550px", width: "100%"
      .TopImage__mainMessage
        人生を変えるフリマアプリ
      .TopImage__subMessage
        FURIMAはだれでもかんたんに
        %br
        出品・購入できるフリマアプリです
      .TopImage__app-googleBox
        .TopImage__app-googleBox__app-storeIcon
          = image_tag "AppleStore-icon-438x129.png", width: "200px", height: "54px"
        .TopImage__app-googleBox__google-playIcon
          = image_tag "google-play-badge.png",width: "200px", height: "79px"
    .MiddleTop
      FURIMAが選ばれる3つの理由
    .PicBox
      .PicBox__ImageLeft
        = image_tag "pict-reason-01.jpg", height:"300px", width: "300px"
        .PicBox__ImageLeft__PicNum1
          %p{style: 'padding-top: 10px;'}
          1
      .PicBox__ImageMiddle
        = image_tag "pict-reason-02.jpg", height:"300px", width: "300px"
        .PicBox__ImageMiddle__PicNum2
          %p{style: 'padding-top: 10px;'}
          2
      .PicBox__ImageRight
        = image_tag "pict-reason-03.jpg", height:"300px", width: "300px"
        .PicBox__ImageRight__PicNum3
          %p{style: 'padding-top: 10px;'}
          3
    .MainMessageBox
      .MainMessageBox__LeftMessage
        %span.s 3分
        ですぐに出品
      .MainMessageBox__MiddleMessage
        %span.s シンプル
        で使いやすい
      .MainMessageBox__RightMessage
        %span.s 手数料
        業界最安
    .SubMessageBox
      .SubMessageBox__LeftSubText
        スマホで入力するだけで簡単に出品！
      .SubMessageBox__MiddleSubText
        簡単作業で検索も購入もスムーズ！
      .SubMessageBox__RightSubText
        最大3%でお得に出品と購入が可能！
    .ContenrMainImage
      = image_tag "bg-topMiddleDl-pict.jpg", height:"400px", width: "100%"
      %h.ContenrMainImage__ContentMainMessage
        会員数日本一位
      .ContenrMainImage__ContentSubMessage
        FURIMAは、フリマアプリで最も人気。
        %br
        出品・購入回数も業界最多です！
        %br
        ほしかったあの商品に出会えるかもしれません。
      .ContenrMainImage__app-googleBox2
        .ContenrMainImage_app-googleBox2__app-storeIcon2
          = image_tag "AppleStore-icon-438x129.png", width: "186px", height: "54px",class:"app-store"
        .ContenrMainImage__app-googleBox2__google-playIcon2
          = image_tag "google-play-badge.png", width: "198px", height: "79px"
    .MiddleTop2
      FURIMAの特徴
    .PicBox2
      .PicBox2__ImageLeft2
        = image_tag "icon-01.png", height:"230px", width: "150px"
      .PicBox2__ImageMiddle2
        = image_tag "icon-03.png", height:"230px", width: "150px"
      .PicBox2__ImageRight2
        = image_tag "icon-04.png", height:"230px", width: "150px"
    .MainMessageBox2
      .MainMessageBox2__LeftMessage2
        簡単に売り買いできる
      .MainMessageBox2__MiddleMessage2
        売上金は即日振込み対応
      .MainMessageBox2__RightMessage2
        様々な支払いに対応
    .SubMessageBox2
      .SubMessageBox2__LeftSubText2
        スマホひとつで
        %br
        簡単に出品・購入が可能！
      .SubMessageBox2__MiddleSubText2
        午前9時までに振込を依頼で
        %br
        翌日に指定の口座に入金可能!
      .SubMessageBox2__RightSubText2
        クレジットカードだけでなく
        %br
        ポイントや売上金など多彩に対応！
    .PicUpCategory
      ピックアップカテゴリー
    .ProsBox
      .ProsBox__MainTopTopic
        新規投稿商品
      .ProsBox__ProsBoxU
        - @products.first(3).each do |product|
          = link_to product_path(product.id) do
            .ProsBox__ProsBoxU__ProLeft
              = image_tag product.images[0].src.url, size: "200x140", class: "aaaaa"
              = product.name
              %br
              = product.conditions
              %br
              -if product.buyer_id.present? 
                .items-box_photo__sold__inner SOLD
              - else
                = product.price
                円
    .PicUpBrand
      ピックアップブランド
    .ProsBox
      .ProsBox__Archiver
        アーカイバ
      .ProsBox__ProsBoxU
        - @products.first(3).each do |product|
          = link_to product_path(product.id) do
            .ProsBox__ProsBoxU__ProLeft
              = image_tag product.images[0].src.url, size: "200x140", class: "aaaaa"
              = product.name
              %br
              = product.conditions
              %br
              -if product.buyer_id.present? 
                .items-box_photo__sold__inner SOLD
              - else
                = product.price
                円
    .ContenrMainImage3
      = image_tag "bg-appBanner-pict.jpg", height:"500px", width: "100%"
      .ContenrMainImage3__ContentMainMessage3
        だれでもかんたん、人生を変えるフリマアプリ
      .ContenrMainImage3__ContentSubMessage3
        今すぐ無料ダウンロード！
      .ContenrMainImage3__app-googleBox3
        .ContenrMainImage3__app-googleBox3__center
          .ContenrMainImage3_app-googleBox3__center__app-storeIcon3
            = image_tag "AppleStore-icon-438x129.png", width: "189px", height: "57px",class: "app-store2"
          .ContenrMainImage3__app-googleBox3__center__google-playIcon3
            = image_tag "google-play-badge.png",width: "199px", height: "80px"
  = render 'layouts/footer'

app/views/products/show.html.haml
= render 'layouts/notifications'
= render 'layouts/header'
.top-show-main
  .top-show-main__middle
    .top-show-main__middle__name
      = @product.name
    .top-show-main__middle__item-box
      .top-show-main__middle__item-box__main
        = image_tag @product.images[0].src.url, size: "560x346"
      .top-show-main__middle__item-box__left
      - @images.each do |image|
        = image_tag image.src.url, size: "114x85", class: "aaaaa"
    .top-show-main__middle__price
      .top-show-main__middle__price__main
        ¥
        = @product.price
      .top-show-main__middle__price__sub
        (税込)送料込み
    .top-show-main__middle__box1
      .top-show-main__middle__box1__purchase
        - if user_signed_in? && current_user.id == @product.user_id
          = link_to "商品の編集", edit_product_path(@product),class: "btn1"
          %br/
          %br/
          or
          %br/
          %br/
          = link_to '削除', product_path(@product), method: :delete, class:"btn2"
        - elsif @product.buyer_id.present? 
          .disabled-button
            売り切れました
        - else
          = link_to "購入画面に進む",  purchase_product_path, class: "btn1"
            
  .top-show-main__middle
    .top-show-main__middle__big-table
      %table.top-show-main-table
        %tr.top-show-main-record
          %th.top-show-main-head
            出品者
          %td.top-show-main-date
            = @product.user.nickname
        %tr.top-show-main-record
          %th.top-show-main-head
            カテゴリー
          %td.top-show-main-date
            = @product.category.name
        %tr.top-show-main-record
          %th.top-show-main-head
            商品説明
          %td.top-show-main-date
            = @product.text
        %tr.top-show-main-record
          %th.top-show-main-head
            商品の状態
          %td.top-show-main-date
            = @product.conditions
        %tr.top-show-main-record
          %th.top-show-main-head
            配送料の負担
          %td.top-show-main-date
            = @product.delivery_charge
        %tr.top-show-main-record
          %th.top-show-main-head
            発送元の地域
          %td.top-show-main-date
            = @product.prefecture
        %tr.top-show-main-record
          %th.top-show-main-head
            発送日の目安
          %td.top-show-main-date
            = @product.delivery_day
    .top-show-main__middle__option
      %li.top-show-main__middle__option__left
        お気に入り
      %li.top-show-main__middle__option__right
        = link_to '不適切な商品の通報', '/#/', class: 'report-btn'
  .top-show-main__comment-box
    .top-show-main__comment-box__main
      .top-show-main__comment-box__main__center
        .top-show-main__comment-box__main__center__super-area
          = form_for "aaa" do |f|
            = f.text_area :content, class: 'top-show-main__comment-box__main__area'
        .top-show-main__comment-box__main__attention
          相手のことを考え丁寧なコメントを心がけましょう。
          %br
          不快な言葉遣いなどは利用制限や退会処分となることがあります。
        .top-show-main__comment-box__main__comment-btn
          コメントする
  .top-show-main__next
    %li.top-show-main__next__left
      = link_to '< 前の商品', '/#/', class: 'back-next-btn'
    %li.top-show-main__next__right
      = link_to '> 次の商品', '/#/' , class: 'back-next-btn'
  .top-show-main__more
    = link_to 'メンズをもっと見る', '/#/', class: 'more-mens'
= render 'layouts/footer'