config/routes.rb
Rails.application.routes.draw do
  root to: 'products#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  resources :top, only: [:index, :new, :create, :show, :edit, :update]
  resources :users, only: [:show,:logout]
  
  namespace :api do
    resources :categories, only: :index, defaults: { format: 'json' }
  end
 

  resources :products do
    member do
      get 'purchase'
      post 'pay'
    end
  end
  
  resources :cards, only: [:new, :show,:index ,:delete] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end
end

app/models/address.rb
class Address < ApplicationRecord
  validates :postal_code, presence: true, length: { maximum: 8, too_long: 'は8文字以内で記入してください'}
  validates :administrative＿divisions, presence: true
  validates :street_number, presence: true
  validates :tel,length: { maximum: 13, too_long: 'は8文字以内で記入してください'}
  
  belongs_to :user,  optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  # validates :customer_id, :card_id, presence: true
  belongs_to :user
end

app/models/categori.rb
class Categori < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  has_ancestry
end

app/models/delivery.rb
class Delivery < ActiveHash::Base
  self.data = [
      {id: '送料込み(出品者負担)', name: '送料込み(出品者負担)'}, {id: '着払い(購入者負担)', name: '着払い(購入者負担)'}
  ]
end

app/models/image.rb
class Image < ApplicationRecord
mount_uploader :src, ImageUploader
belongs_to :product
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :todoufuken
end

app/models/product.rb
class Product < ApplicationRecord

has_many :images, dependent: :destroy
accepts_nested_attributes_for :images, allow_destroy: true

belongs_to :category
belongs_to :user
belongs_to :seller, class_name: "User", optional: true
belongs_to :buyer, class_name: "User", optional: true

validates :delivery_charge, :prefecture, :delivery_day, :text, :price, presence: true
validates :name,        presence: true,
                        length: { minimum: 1, maximum: 40 }
validates :conditions,  presence: true,
                        length: { minimum: 1, maximum: 1000 }

validates :images,      presence: true

  validates :name, :price, :text, presence: true
extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :todoufuken
  belongs_to_active_hash :delivery

end

app/models/todoufuken.rb
class Todoufuken < ActiveHash::Base
  self.data = [
      {id: '北海道', name: '北海道'}, {id: '青森県', name: '青森県'}, {id: '岩手県', name: '岩手県'},
      {id: '宮城県', name: '宮城県'}, {id: '秋田県', name: '秋田県'}, {id: '山形県', name: '山形県'},
      {id: '福島県', name: '福島県'}, {id: '茨城県', name: '茨城県'}, {id: '栃木県', name: '栃木県'},
      {id: '群馬県', name: '群馬県'}, {id: '埼玉県', name: '埼玉県'}, {id: '千葉県', name: '千葉県'},
      {id: '東京都', name: '東京都'}, {id: '神奈川県', name: '神奈川県'}, {id: '新潟県', name: '新潟県'},
      {id: '富山県', name: '富山県'}, {id: '石川県', name: '石川県'}, {id: '福井県', name: '福井県'},
      {id: '山梨県', name: '山梨県'}, {id: '長野県', name: '長野県'}, {id: '岐阜県', name: '岐阜県'},
      {id: '静岡県', name: '静岡県'}, {id: '愛知県', name: '愛知県'}, {id: '三重県', name: '三重県'},
      {id: '滋賀県', name: '滋賀県'}, {id: '京都府', name: '京都府'}, {id: '大阪府', name: '大阪府'},
      {id: '兵庫県', name: '兵庫県'}, {id: '奈良県', name: '奈良県'}, {id: '和歌山県', name: '和歌山県'},
      {id: '鳥取県', name: '鳥取県'}, {id: '島根県', name: '島根県'}, {id: '岡山県', name: '岡山県'},
      {id: '広島県', name: '広島県'}, {id: '山口県', name: '山口県'}, {id: '徳島県', name: '徳島県'},
      {id: '香川県', name: '香川県'}, {id: '愛媛県', name: '愛媛県'}, {id: '高知県', name: '高知県'},
      {id: '福岡県', name: '福岡県'}, {id: '佐賀県', name: '佐賀県'}, {id: '長崎県', name: '長崎県'},
      {id: '熊本県', name: '熊本県'}, {id: '大分県', name: '大分県'}, {id: '宮崎県', name: '宮崎県'},
      {id: '鹿児島県', name: '鹿児島県'}, {id: '沖縄県', name: '沖縄県'}
  ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true
  validates :email, presence: true
  validates :password, presence: true
  validates :family_name, presence: true,format: { with: /\A[一-龥]+\z/, message: 'は漢字を入力してください'}
  validates :first_name, presence: true,format:{ with: /\A[一-龥]+\z/, message: 'は漢字を入力してください'}
  validates :hurigana_family_name, presence: true,format:{ with: /\A[ぁ-んー－]+\z/, message: 'は全角平仮名を入力してください'}
  validates :hurigana_first_name, presence: true,format:{ with: /\A[ぁ-んー－]+\z/, message: 'は全角平仮名を入力してください'}
  validates :birth_year, presence: true
  validates :birth_month, presence: true
  validates :birth_date, presence: true



  has_many :cards
  has_one :address
  accepts_nested_attributes_for :address
  
  has_many :comennts
  has_many :favorites
  has_many :products
         
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  require 'payjp'

  def index
  end
  
  def new
    card = Card.where(user_id: current_user.id)
    redirect_to action: "show" if card.exists?
  end
  
  def pay
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create( # ここで先ほど生成したトークンを顧客情報と紐付け、PAY.JP管理サイトに送信
        description: 'test',
        email: current_user.email,
        card: params['payjp-token'],
        metadata: {user_id: current_user.id}
      )
    @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "show"
        flash[:notice] = 'クレジットカードの登録が完了しました'
      else
        redirect_to action: "pay"
        flash[:alert] = 'クレジットカード登録に失敗しました'
      end
    end
  end

  def delete #PayjpとCardデータベースを削除します
    card = Card.where(user_id: current_user.id).first
    if card.blank?
    else
      Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
      flash[:notice] = "削除しました。"
    end
      redirect_to action: "new"
  end


  def show #Cardのデータpayjpに送り情報を取り出します
    card = Card.where(user_id: current_user.id).first
    if card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end


  
end

  

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @products = Product.all.includes(:images)
  end

  def new
    @product = Product.new
  end

  def create
    Product.create(product_params)
  end




  

  def show
  end  


 private

  def product_params
    params.require(:products).permit(:name, :conditions, :delivery_charge, :prefecture, :delivery_day, :text, :user_id, :category_id, :brand_id, :price)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def show
    @user = User.where(user_id: current_user.id)
  end
  
  def logout
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/card_helper.rb
module CardHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.haml
.TopPageFooter
  %ul.TopPageFooter1
    %li.F1
      %h1.AboutFURIMA{style: 'padding: 70px 0 12px; text-align: center; font-weight :bold; font-size: 20px'}
        FURIMAについて
      %ul 
        %li{style: 'padding-top: 10px; text-align: center'}
          = link_to "会社概要", "#", class:"about1"
        %li{style: 'padding-top: 10px; text-align: center'}
          = link_to "プライバシーポリシー", "#", class:"about1"
        %li{style: 'padding-top: 10px; text-align: center'}
          = link_to "FURIMA規約", "#", class:"about1"
        %li{style: 'padding-top: 10px; text-align: center'}
          = link_to "ポイントに関する規約", "#", class:"about1"
    %li.F2
      %h1.SeeFURIMA{style: 'padding: 70px 0 12px; text-align: center; font-weight :bold; font-size: 20px'}
        FURIMAを見る
      %ul 
        %li{style: 'padding-top: 10px; text-align: center'}
          = link_to "カテゴリー一覧", "#", class:"about1"
        %li{style: 'padding-top: 10px; text-align: center'}
          = link_to "ブランド一覧", "#", class:"about1"
    %li.F3
      %h1.HelpGuide{style: 'padding: 70px 0 12px; text-align: center; font-weight :bold; font-size: 20px'}
        ヘルプ＆ガイド
      %ul 
        %li{style: 'padding-top: 10px; text-align: center'}
          = link_to "FURIMAガイド", "#", class:"about1"
        %li{style: 'padding-top: 10px; text-align: center'}
          = link_to "FURIMAロゴ利用ガイドライン", "#", class:"about1"
        %li{style: 'padding-top: 10px; text-align: center'}
          = link_to "お知らせ", "#", class:"about1"
.WhiteFURIMAicon
  = image_submit_tag "logo-white.png", height:"47px", width: "160px"
  %p.sub © FURIMA

%button.fixed_btn
  %h1 出品する
  = link_to new_product_path do
    = image_tag "icon_camera.png", height: "62%", width: "62%"
    

app/views/layouts/_header.html.haml
.top_body
  .headerBox
    .headerBox__upperBox
      .headerBox__upperBox__furimaIcon
        = link_to root_path do
          = image_tag "logo.png", hight:"60px", width: "160px"
      .headerBox__upperBox__search
        = form_tag("#", method: :get) do
          = text_field_tag("text", "",{placeholder: "キーワードから探す", class: "text111"})
        .headerBox__upperBox__search__searchIcon 
          = image_submit_tag "icon-search 1.png",width: "50px", height: "44px"
    .headerBox__lowerBox  
      .headerBox__lowerBox__leftBox
        .headerBox__lowerBox__leftBox__category
          カテゴリー
        .headerBox__lowerBox__leftBox__brand
          ブランド
      .headerBox__lowerBox__rightBox
        .headerBox__lowerBox__rightBox__login
          - if user_signed_in?
            .headerBox__lowerBox__rightBox__login__registration
              = link_to "ログアウト",destroy_user_session_path, method: :delete, class: "logout_btn"
            .headerBox__lowerBox__rightBox__login__registration
              = link_to "マイページ",user_path(current_user),class: "logout_btn"
          - else
            .headerBox__lowerBox__rightBox__login__registration
              = link_to "ログイン", new_user_session_path, class: "login_btn"
            .headerBox__lowerBox__rightBox__login__registration
              = link_to "新規登録", new_user_registration_path,class: "login_btn"

app/views/layouts/_notifications.html.haml
.notification
 - if flash[:notice]
  %p= flash[:notice]
 - else flash[:notice]
  %p= flash[:notice]

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FreemarketSample67d
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
    %script{type: "text/javascript"} Payjp.setPublicKey('pk_test_8b290bb46d1e1db9a3ed5529');
  %body

    = yield
 